project:
  type: website
  output-dir: docs

website:
  navbar:
    title: "Paul Robinson"
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: linux-resources.qmd
        text: Linux resources

format:
  html:
    theme:
      light: minty
      dark: solar
    css: styles.css
    toc: true
    page-layout: full

editor: visual

