project:
  type: website
  output-dir: docs

website:
  navbar:
    title: "Paul Robinson"
    left:
      - href: index.qmd
        text: Home
      - statsposts.qmd
      - sl-wildlife-posts.qmd
      - wildlife-tourism.qmd
      - linux-posts.qmd
      

format:
  html:
    theme:
      light: minty
      dark: solar
    css: styles.css
    toc: true
    page-layout: full

editor: visual

