project:
  type: website
  output-dir: docs

website:
  navbar:
    title: "Paul Robinson"
    background: "#0d7680"
    left:
      - href: index.qmd
        text: Home
      - statsposts.qmd
      - sl-wildlife-posts.qmd
      - wildlife-tourism.qmd
      - linux-posts.qmd
      - icon: github
        href: https://github.com/paulauvirage
        target: _blank
  page-footer: 
    background: "#0d7680"
    left: Written and designed by Paul Robinson, licenced under [CC BY-NC_SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)
    right: This website is built with [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/paulauvirage/paulauvirage.github.io){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}
      

format:
  html:
    theme: 
      light: [minty, styles.scss]
      dark: [solar]
    mainfont: "Red Hat"
    toc: true
    toc-depth: 3
    toc-expand: 2
    number-sections: true
    number-depth: 3
    page-layout: full
    code-copy: true
    code-fold: true
    code-summary: "Show the code"
    code-block-border-left: "#900c3f"
    nav-tabs-link-active-border-color: "#900c3f"
    mermaid:
      theme: forest
    #css: styles.scss


editor: source

